export const HOUSE_LIST_REQUEST = "HOUSE_LIST_REQUEST";
export const HOUSE_LIST_SUCCESS = "HOUSE_LIST_SUCCESS";
export const HOUSE_LIST_FAIL = "HOUSE_LIST_FAIL";

export const HOUSE_DETAIL_REQUEST = "HOUSE_DETAIL_REQUEST";
export const HOUSE_DETAIL_SUCCESS = "HOUSE_DETAIL_SUCCESS";
export const HOUSE_DETAIL_FAIL = "HOUSE_DETAIL_FAIL";

export const HOUSE_CREATE_REQUEST = "HOUSE_CREATE_REQUEST";
export const HOUSE_CREATE_SUCCESS = "HOUSE_CREATE_SUCCESS";
export const HOUSE_CREATE_FAIL = "HOUSE_CREATE_FAIL";

export const HOUSE_UPDATE_REQUEST = "HOUSE_UPDATE_REQUEST";
export const HOUSE_UPDATE_SUCCESS = "HOUSE_UPDATE_SUCCESS";
export const HOUSE_UPDATE_FAIL = "HOUSE_UPDATE_FAIL";

export const HOUSE_DELETE_REQUEST = "HOUSE_DELETE_REQUEST";
export const HOUSE_DELETE_SUCCESS = "HOUSE_DELETE_SUCCESS";
export const HOUSE_DELETE_FAIL = "HOUSE_DELETE_FAIL";
