export const HOUSE_BOOKING_CREATE_REQUEST = "HOUSE_BOOKING_CREATE_REQUEST";
export const HOUSE_BOOKING_CREATE_SUCCESS = "HOUSE_BOOKING_CREATE_SUCCESS";
export const HOUSE_BOOKING_CREATE_FAIL = "HOUSE_BOOKING_CREATE_FAIL";
